nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        forced_allow_origin_value: '*'
    paths:
        '^/api/':
            allow_origin: [ '*' ]
            allow_headers: [ '*' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
            max_age: 3600